name: Byg et Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker_image_pipeline:
    name: Build Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      IMAGE_NAME: go-userservice
    steps:
      - uses: actions/checkout@v4

      - name: Set dynamic image version
        id: vars
        run: echo "IMAGE_VERSION=$(date +%Y%m%d)-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . -f GO-UserService/Dockerfile \
          -t ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_VERSION} \
          -t ${DOCKER_USER}/${IMAGE_NAME}:compose

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_VERSION}
          docker push ${DOCKER_USER}/${IMAGE_NAME}:compose
